"""blocked field for publications

Revision ID: 36776cf9c0c4
Revises: 43345d8992f7
Create Date: 2020-12-23 19:40:57.295099

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '36776cf9c0c4'
down_revision = '43345d8992f7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('publication', sa.Column('blocked', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('publication', 'blocked')
    # ### end Alembic commands ###
