"""add user id

Revision ID: 43345d8992f7
Revises: aa2a6c05e129
Create Date: 2020-12-16 19:55:03.291546

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '43345d8992f7'
down_revision = 'aa2a6c05e129'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'publication_question', sa.Column('user_id', sa.Integer(), nullable=True)
    )
    op.execute("UPDATE publication_question SET user_id = 1")
    with op.batch_alter_table("publication_question") as batch_op:
        batch_op.alter_column('user_id', nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('publication_question', 'user_id')
    # ### end Alembic commands ###
