"""add loc geography

Revision ID: 6893c6266324
Revises: c9f89a780c0d
Create Date: 2020-11-18 01:54:14.871152

"""
import geoalchemy2
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '6893c6266324'
down_revision = 'c9f89a780c0d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    bind = op.get_bind()

    if str(bind.engine.url).startswith("sqlite"):
        op.execute("select AddGeometryColumn('publication','loc',4326,'POINT','XY',0)")
    else:
        op.add_column(
            'publication',
            sa.Column(
                'loc',
                geoalchemy2.types.Geography(
                    geometry_type='POINT',
                    srid=4326,
                    from_text='ST_GeogFromText',
                    name='geography',
                ),
                nullable=True,
            ),
        )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    bind = op.get_bind()

    if str(bind.engine.url).startswith("sqlite"):
        op.execute("select DiscardGeometryColumn('publication', 'loc')")
    else:
        with op.batch_alter_table("publication") as batch_op:
            batch_op.drop_column('loc')
    # ### end Alembic commands ###
