"""add images model

Revision ID: 89dc2174448e
Revises: bdb71236b584
Create Date: 2020-12-12 20:41:44.458329

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils

# revision identifiers, used by Alembic.
revision = '89dc2174448e'
down_revision = 'bdb71236b584'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'publication_image',
        sa.Column(
            'id', sqlalchemy_utils.types.uuid.UUIDType(binary=False), nullable=False
        ),
        sa.Column('url', sa.String(), nullable=False),
        sa.Column('publication_id', sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ['publication_id'],
            ['publication.id'],
        ),
        sa.PrimaryKeyConstraint('id'),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('publication_image')
    # ### end Alembic commands ###
