"""add star model

Revision ID: 9ae88ecbc099
Revises: 36776cf9c0c4
Create Date: 2021-01-02 01:03:43.146732

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '9ae88ecbc099'
down_revision = '36776cf9c0c4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'publication_star',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('user_id', sa.Integer(), nullable=False),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.Column('publication_id', sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(['publication_id'], ['publication.id'],),
        sa.PrimaryKeyConstraint('id'),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('publication_star')
    # ### end Alembic commands ###
