"""add replied at

Revision ID: aa2a6c05e129
Revises: a7024a39f57a
Create Date: 2020-12-16 12:38:56.635976

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = 'aa2a6c05e129'
down_revision = 'a7024a39f57a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'publication_question', sa.Column('replied_at', sa.DateTime(), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("publication_question") as batch_op:
        batch_op.drop_column('replied_at')
    # ### end Alembic commands ###
