"""add publication date column

Revision ID: bdb71236b584
Revises: 6893c6266324
Create Date: 2020-11-30 02:26:42.873396

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = 'bdb71236b584'
down_revision = '6893c6266324'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'publication', sa.Column('publication_date', sa.DateTime(), nullable=True)
    )
    op.execute("""update "publication" set publication_date = 'now()'""")
    with op.batch_alter_table("publication") as batch_op:
        batch_op.alter_column("publication_date", nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("publication") as batch_op:
        batch_op.drop_column('publication_date')
    # ### end Alembic commands ###
