"""add user_id to publications model

Revision ID: c9f89a780c0d
Revises: 8820e9d0b161
Create Date: 2020-11-17 16:39:14.627383

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c9f89a780c0d'
down_revision = '8820e9d0b161'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('publication', sa.Column('user_id', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('publication', 'user_id')
    # ### end Alembic commands ###
