"""add user_id to publications model

Revision ID: c9f89a780c0d
Revises: 8820e9d0b161
Create Date: 2020-11-17 16:39:14.627383

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = 'c9f89a780c0d'
down_revision = '8820e9d0b161'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("publication", sa.Column('user_id', sa.Integer(), nullable=True))
    op.execute("update publication set user_id = 1")
    with op.batch_alter_table("publication") as batch_op:
        batch_op.alter_column('user_id', nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("publication") as batch_op:
        batch_op.drop_column('user_id')
    # ### end Alembic commands ###
