"""blockchain fields

Revision ID: fd36afc3738d
Revises: 9ae88ecbc099
Create Date: 2021-02-14 16:40:47.043988

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

from publications_microservice.constants import BlockChainStatus

# revision identifiers, used by Alembic.
revision = 'fd36afc3738d'
down_revision = '9ae88ecbc099'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    status_enum = postgresql.ENUM(
        'CONFIRMED', 'DENIED', 'PENDING', 'UNSET', 'ERROR', name='blockchain_status'
    )
    status_enum.create(op.get_bind())

    op.add_column(
        'publication', sa.Column('blockchain_id', sa.Integer(), nullable=True)
    )
    op.add_column(
        'publication',
        sa.Column(
            'blockchain_status',
            status_enum,
            nullable=False,
            default=BlockChainStatus.UNSET.value,
            server_default=BlockChainStatus.UNSET.value,
        ),
    )
    op.add_column(
        'publication',
        sa.Column('blockchain_transaction_hash', sa.String(length=512), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('publication', 'blockchain_transaction_hash')
    op.drop_column('publication', 'blockchain_status')
    op.drop_column('publication', 'blockchain_id')
    pp.execute("DROP TYPE blockchain_status")
    # ### end Alembic commands ###
