version: '3.7'
services:
    postgres:
        image: postgis/postgis:11-2.5-alpine
        environment:
          - POSTGRES_USER=publications_microservice
          - POSTGRES_PASSWORD=publications_microservice
          - POSTGRES_DB=publications_microservice
          - PGDATA=/var/lib/postgresql/data/pgdata
        ports:
          - 54321:5432
        volumes:
          - /var/lib/postgresql/data/pgdata
        logging:
            options:
                max-size: 10m
                max-file: "3"
    api:
      container_name: publications_microservice_api
      depends_on:
        - postgres
      build:
        context: ../
        dockerfile: Dockerfile
      ports:
        - "5000:5000"
      environment:
        - DATABASE_URL=postgres://publications_microservice:publications_microservice@postgres/publications_microservice
      entrypoint: /app/docker-compose/api-entrypoint.sh
